[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
lib_deps =
  https://github.com/ESP32Async/ESPAsyncWebServer.git
  https://github.com/ESP32Async/AsyncTCP.git
  bblanchon/ArduinoJson@^7.0.4
  miguelbalboa/MFRC522@^1.4.10
  knolleary/PubSubClient@^2.8
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
test_framework = unity
test_build_src = yes
